server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mygit-009/76
          search-paths: config
          username: mygit-009
          passphrase: zq242424
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/